CREATE TABLE dbo.CountryMaster(
    CountryId       INT             NOT NULL IDENTITY(1,1), -- Automatically generated Id
    CountryCode     NVARCHAR(10)    NOT NULL PRIMARY KEY,  -- ISO3166 Code
	CountryName     NVARCHAR(255)   NOT NULL, -- Short name
	OfficialName    NVARCHAR(1000)  NOT NULL, -- Full official name
	PhoneCode       NVARCHAR(100)   NOT NULL, -- Stored as CSV
    IsDeleted       BIT             NOT NULL, -- Boolean to turn off a country from displaying

    -- The below fields are optional
    -- used for auditing in case staff are allowed to edit countries
    
	ModifiedBy      NVARCHAR(255),
	ModifiedUTC     DATETIME,
	CreatedBy       NVARCHAR(255),
	CreatedUTC      DATETIME
)
GO

-- Temp variables to store values to be inserted
DECLARE @IsDeleted   BIT,
        @UserId      NVARCHAR(255),
        @UTCDate     DATETIME

SET @IsDeleted = 0
SET @UserId = N'0'
SET @UTCDate = GETUTCDATE()

-- Insert script

INSERT INTO dbo.CountryMaster
    (
        CountryCode,
        CountryName,
        OfficialName,
        PhoneCode,
        IsDeleted,
        ModifiedBy,
        ModifiedUTC,
        CreatedBy,
        CreatedUTC
    )
VALUES
    (N'AF', N'Afghanistan', N'Islamic Republic of Afghanistan', N'93', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AL', N'Albania', N'Republic of Albania', N'355', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'DZ', N'Algeria', N'People''s Democratic Republic of Algeria', N'213', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AD', N'Andorra', N'Principality of the Valleys of Andorra', N'316', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AO', N'Angola', N'Republic of Angola', N'244', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AG', N'Antigua and Barbuda', N'Antigua and Barbuda', N'1-268', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AR', N'Argentina', N'Argentine Republic', N'54', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AM', N'Armenia', N'Republic of Armenia', N'378', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AU', N'Australia', N'Commonwealth of Australia', N'61', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AT', N'Austria', N'Republic of Austria', N'43', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AZ', N'Azerbaijan', N'Republic of Azerbaijan ', N'994', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BS', N'The Bahamas', N'Commonwealth of The Bahamas', N'1 242', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BH', N'Bahrain', N'Kingdom of Bahrain', N'973', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BD', N'Bangladesh', N'People''s Republic of Bangladesh', N'880', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BB', N'Barbados', N'Barbados', N'1-246', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BY', N'Belarus', N'Republic of Belarus', N'375', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BE', N'Belgium', N'Kingdom of Belgium', N'32', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BZ', N'Belize', N'Belize', N'501', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BJ', N'Benin', N'Republic of Benin', N'229', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BT', N'Bhutan', N'Kingdom of Bhutan', N'975', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BO', N'Bolivia', N'Plurinational State of Bolivia', N'591', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BA', N'Bosnia and Herzegovina', N'Bosnia and Herzegovina', N'387', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BW', N'Botswana', N'Republic of Botswana', N'267', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BR', N'Brazil', N'Federative Republic of Brazil', N'55', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BN', N'Brunei', N'Nation of Brunei, the Abode of Peace', N'673', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BG', N'Bulgaria', N'Republic of Bulgaria', N'359', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BF', N'Burkina Faso', N'Burkina Faso', N'226', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'BI', N'Burundi', N'Republic of Burundi', N'257', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CV', N'Cabo Verde', N'Republic of Cabo Verde', N'238', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KH', N'Cambodia', N'Kingdom of Cambodia', N'855', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CM', N'Cameroon', N'Republic of Cameroon', N'237', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CA', N'Canada', N'Canada', N'1', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CF', N'Central African Republic', N'Central African Republic', N'236', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TD', N'Chad', N'Republic of Chad', N'235', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CL', N'Chile', N'Republic of Chile', N'56', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CN', N'China', N'People''s Republic of China', N'86', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CO', N'Colombia', N'Republic of Colombia', N'57', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KM', N'Comoros', N'Union of the Comoros', N'269', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CG', N'Congo', N'Republic of the Congo', N'242', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CR', N'Costa Rica', N'Republic of Costa Rica', N'506', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CI', N'Ivory Coast', N'Republic of Côte d''Ivoire', N'225', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'HR', N'Croatia', N'Republic of Croatia', N'385', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CU', N'Cuba', N'Republic of Cuba', N'53', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CY', N'Cyprus', N'Republic of Cyprus', N'357', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CZ', N'Czech Republic', N'Czech Republic', N'420', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KP', N'North Korea', N'Democratic People''s Republic of Korea', N'850', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CD', N'DR Congo', N'Democratic Republic of the Congo', N'243', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'DK', N'Denmark', N'Kingdom of Denmark', N'45', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'FO', N'Faroe Islands', N'Faroe Islands', N'298', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GL', N'Greenland', N'Greenland', N'299', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'DJ', N'Djibouti', N'Republic of Djibouti', N'253', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'DM', N'Dominica', N'Commonwealth of Dominica', N'1-767', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'DO', N'Dominican Republic', N'Dominican Republic', N'1-809,1-829,1-849', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'EC', N'Ecuador', N'Republic of Ecuador', N'593', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'EG', N'Egypt', N'Arab Republic of Egypt', N'20', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SV', N'El Salvador', N'Republic of El Salvador', N'503', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GQ', N'Equatorial Guinea', N'Republic of Equatorial Guinea', N'240', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ER', N'Eritrea', N'State of Eritrea', N'291', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'EE', N'Estonia', N'Republic of Estonia', N'372', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ET', N'Ethiopia', N'Federal Democratic Republic of Ethiopia ', N'251', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SZ', N'Swaziland', N'Kingdom of eSwatini', N'268', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'FJ', N'Fiji', N'Republic of Fiji', N'679', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'FI', N'Finland', N'Republic of Finland', N'358', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'FR', N'France', N'French Republic', N'33', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GA', N'Gabon', N'Gabonese Republic', N'241', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GM', N'The Gambia', N'Republic of the Gambia', N'220', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GE', N'Georgia', N'Georgia', N'995', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'DE', N'Germany', N'Federal Republic of Germany', N'49', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GH', N'Ghana', N'Republic of Ghana', N'233', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GR', N'Greece', N'Hellenic Republic', N'30', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GD', N'Grenada', N'Grenada', N'1-473', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GT', N'Guatemala', N'Republic of Guatemala', N'502', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GN', N'Guinea', N'Republic of Guinea', N'224', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GW', N'Guinea-Bissau', N'Republic of Guinea-Bissau', N'245', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GY', N'Guyana', N'Co-operative Republic of Guyana', N'592', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'HT', N'Haiti', N'Republic of Haiti', N'509', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'HN', N'Honduras', N'Republic of Honduras', N'504', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'HU', N'Hungary', N'Hungary', N'36', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IS', N'Iceland', N'Iceland', N'358', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IN', N'India', N'Republic of India', N'91', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ID', N'Indonesia', N'Republic of Indonesia', N'62', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IR', N'Iran', N'Islamic Republic of Iran', N'98', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IQ', N'Iraq', N'Republic of Iraq', N'964', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IE', N'Ireland', N'Republic of Ireland', N'353', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IL', N'Israel', N'State of Israel', N'972', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'IT', N'Italy', N'Italian Republic', N'39', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'JM', N'Jamaica', N'Jamaica', N'1-876,1-658', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'JP', N'Japan', N'Japan', N'81', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'JO', N'Jordan', N'The Hashemite Kingdom of Jordan', N'962', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KZ', N'Kazakhstan', N'Republic of Kazakhstan', N'7', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'EAT', N'Kenya', N'Republic of Kenya', N'254', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KI', N'Kiribati', N'Republic of Kiribati', N'686', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KW', N'Kuwait', N'State of Kuwait', N'965', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KGT', N'Kyrgyzstan', N'Kyrgyz Republic', N'996', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LA', N'Laos', N'Lao People''s Democratic Republic', N'856', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LV', N'Latvia', N'Republic of Latvia', N'371', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LB', N'Lebanon', N'Lebanese Republic', N'961', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LS', N'Lesotho', N'Kingdom of Lesotho', N'266', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LR', N'Liberia', N'Republic of Liberia', N'231', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LY', N'Libya', N'State of Libya', N'218', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LI', N'Liechtenstein', N'Principality of Liechtenstein', N'423', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LT', N'Lithuania', N'Republic of Lithuania', N'370', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LU', N'Luxembourg', N'Grand Duchy of Luxembourg', N'352', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MG', N'Madagascar', N'Republic of Madagascar', N'261', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MW', N'Malawi', N'Republic of Malawi', N'265', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MY', N'Malaysia', N'Malaysia', N'60', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MV', N'Maldives', N'Republic of Maldives', N'960', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ML', N'Mali', N'Republic of Mali', N'223', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MT', N'Malta', N'Republic of Malta', N'356', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MH', N'Marshall Islands', N'Republic of the Marshall Islands', N'692', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MR', N'Mauritania', N'Islamic Republic of Mauritania', N'222', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MU', N'Mauritius', N'Republic of Mauritius', N'230', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MX', N'Mexico', N'United Mexican States', N'52', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'FM', N'Federated States of Micronesia', N'Federated States of Micronesia', N'691', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MC', N'Monaco', N'Principality of Monaco', N'377', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MN', N'Mongolia', N'Mongolia', N'976', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ME', N'Montenegro', N'Montenegro', N'382', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MA', N'Morocco', N'Kingdom of Morocco', N'212', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MZ', N'Mozambique', N'Republic of Mozambique', N'258', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'MM', N'Myanmar', N'Republic of the Union of Myanmar', N'95', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NA', N'Namibia', N'Republic of Namibia', N'264', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NR', N'Nauru', N'Republic of Nauru', N'674', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NP', N'Nepal', N'Federal Democratic Republic of Nepal', N'977', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NL', N'Netherlands', N'Kingdom of the Netherlands', N'31,297,599,1-721', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NZ', N'New Zealand', N'New Zealand', N'64', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NI', N'Nicaragua', N'Republic of Nicaragua', N'505', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NE', N'Niger', N'Republic of the Niger', N'227', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NG', N'Nigeria', N'Federal Republic of Nigeria', N'234', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'NO', N'Norway', N'Kingdom of Norway', N'47', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'OM', N'Oman', N'Sultanate of Oman', N'968', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PK', N'Pakistan', N'Islamic Republic of Pakistan', N'92', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PW', N'Palau', N'Republic of Palau', N'680', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PS', N'Palestine', N'State of Palestine', N'970', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PA', N'Panama', N'Republic of Panama', N'507', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PG', N'Papua New Guinea', N'Independent State of Papua New Guinea', N'675', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PY', N'Paraguay', N'Republic of Paraguay', N'595', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PE', N'Peru', N'Republic of Peru', N'51', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PH', N'Philippines', N'Republic of the Philippines ', N'63', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PL', N'Poland', N'Republic of Poland', N'48', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'PT', N'Portugal', N'Portuguese Republic', N'351', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'QA', N'Qatar', N'State of Qatar', N'974', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'RO', N'Romania', N'Romania', N'40', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'RU', N'Russia', N'Russian Federation', N'7', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'RW', N'Rwanda', N'Republic of Rwanda', N'250', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'KN', N'Saint Kitts and Nevis', N'Federation of Saint Christopher and Nevis', N'1869', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LC', N'Saint Lucia', N'Saint Lucia', N'1758', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'VC', N'Saint Vincent', N'Saint Vincent and the Grenadines', N'1784', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'WS', N'Samoa', N'Independent State of Samoa', N'685', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SM', N'San Marino', N'Republic of San Marino', N'378', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ST', N'São Tomé and Príncipe', N'Democratic Republic of São Tomé and Príncipe', N'239', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SA', N'Saudi Arabia', N'Kingdom of Saudi Arabia', N'966', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SN', N'Senegal', N'Republic of Senegal', N'221', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'RS', N'Serbia', N'Republic of Serbia', N'381', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SC', N'Seychelles', N'Republic of Seychelles', N'248', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SL', N'Sierra Leone', N'Republic of Sierra Leone', N'232', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SG', N'Singapore', N'Republic of Singapore', N'65', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SK', N'Slovakia', N'Slovak Republic', N'421', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SI', N'Slovenia', N'Republic of Slovenia', N'386', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SB', N'Solomon Islands', N'Solomon Islands', N'677', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SO', N'Somalia', N'Federal Republic of Somalia', N'252', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ZA', N'South Africa', N'Republic of South Africa', N'27', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SS', N'South Sudan', N'Republic of South Sudan', N'211', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ES', N'Spain', N'Kingdom of Spain', N'34', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'LK', N'Sri Lanka', N'Democratic Socialist Republic of Sri Lanka', N'94', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SD', N'North Sudan', N'Republic of the Sudan', N'249', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SR', N'Suriname', N'Republic of Suriname', N'597', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SE', N'Sweden', N'Kingdom of Sweden', N'46', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'CH', N'Switzerland', N'Swiss Confederation', N'41', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'SY', N'Syria', N'Syrian Arab Republic', N'963', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TJ', N'Tajikistan', N'Republic of Tajikistan', N'992', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TZ', N'Tanzania', N'United Republic of Tanzania', N'255', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TH', N'Thailand', N'Kingdom of Thailand', N'66', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TG', N'Togo', N'Togolese Republic', N'228', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TO', N'Tonga', N'Kingdom of Tonga', N'676', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TT', N'Trinidad and Tobago', N'Republic of Trinidad and Tobago', N'1 868', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TN', N'Tunisia', N'Republic of Tunisia', N'216', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TR', N'Turkey', N'Republic of Turkey', N'90', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TM', N'Turkmenistan', N'Turkmenistan', N'993', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'TV', N'Tuvalu', N'Tuvalu', N'65', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'UG', N'Uganda', N'Republic of Uganda', N'256', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'UA', N'Ukraine', N'Ukraine', N'380', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'AE', N'United Arab Emirates', N'United Arab Emirates', N'971', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'GB', N'United Kingdom', N'United Kingdom', N'44', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'US', N'United States', N'United States of America', N'1', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'UY', N'Uruguay', N'Oriental Republic of Uruguay', N'598', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'UZ', N'Uzbekistan', N'Republic of Uzbekistan', N'998', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'VU', N'Vanuatu', N'Republic of Vanuatu', N'678', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'VA', N'Vatican City', N'State of Vatican City', N'349', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'VE', N'Venezuela', N'Bolivarian Republic of Venezuela', N'58', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'VN', N'Vietnam', N'Socialist Republic of Vietnam', N'84', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'YE', N'Yemen', N'Republic of Yemen', N'967', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ZM', N'Zambia', N'Republic of Zambia', N'260', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate),
    (N'ZW', N'Zimbabwe', N'Republic of Zimbabwe', N'263', @IsDeleted, @UserId, @UTCDate, @UserId, @UTCDate)
GO
