INSERT INTO dbo.CountryMaster
    (
        CountryId,
        CountryCode, -- ISO3166 Code
        CountryName, -- Short name
        OfficialName,
        PhoneCode -- Stored as csv
    )
VALUES
    (1, N'AF', N'Afghanistan', N'Islamic Republic of Afghanistan', N'93'),
    (2, N'AL', N'Albania', N'Republic of Albania', N'355'),
    (3, N'DZ', N'Algeria', N'People''s Democratic Republic of Algeria', N'213'),
    (4, N'AD', N'Andorra', N'Principality of the Valleys of Andorra', N'316'),
    (5, N'AO', N'Angola', N'Republic of Angola', N'244'),
    (6, N'AG', N'Antigua and Barbuda', N'Antigua and Barbuda', N'1-268'),
    (7, N'AR', N'Argentina', N'Argentine Republic', N'54'),
    (8, N'AM', N'Armenia', N'Republic of Armenia', N'378'),
    (9, N'AU', N'Australia', N'Commonwealth of Australia', N'61'),
    (10, N'AT', N'Austria', N'Republic of Austria', N'43'),
    (11, N'AZ', N'Azerbaijan', N'Republic of Azerbaijan ', N'994'),
    (12, N'BS', N'The Bahamas', N'Commonwealth of The Bahamas', N'1 242'),
    (13, N'BH', N'Bahrain', N'Kingdom of Bahrain', N'973'),
    (14, N'BD', N'Bangladesh', N'People''s Republic of Bangladesh', N'880'),
    (15, N'BB', N'Barbados', N'Barbados', N'1-246'),
    (16, N'BY', N'Belarus', N'Republic of Belarus', N'375'),
    (17, N'BE', N'Belgium', N'Kingdom of Belgium', N'32'),
    (18, N'BZ', N'Belize', N'Belize', N'501'),
    (19, N'BJ', N'Benin', N'Republic of Benin', N'229'),
    (20, N'BT', N'Bhutan', N'Kingdom of Bhutan', N'975'),
    (21, N'BO', N'Bolivia', N'Plurinational State of Bolivia', N'591'),
    (22, N'BA', N'Bosnia and Herzegovina', N'Bosnia and Herzegovina', N'387'),
    (23, N'BW', N'Botswana', N'Republic of Botswana', N'267'),
    (24, N'BR', N'Brazil', N'Federative Republic of Brazil', N'55'),
    (25, N'BN', N'Brunei', N'Nation of Brunei, the Abode of Peace', N'673'),
    (26, N'BG', N'Bulgaria', N'Republic of Bulgaria', N'359'),
    (27, N'BF', N'Burkina Faso', N'Burkina Faso', N'226'),
    (28, N'BI', N'Burundi', N'Republic of Burundi', N'257'),
    (29, N'CV', N'Cabo Verde', N'Republic of Cabo Verde', N'238'),
    (30, N'KH', N'Cambodia', N'Kingdom of Cambodia', N'855'),
    (31, N'CM', N'Cameroon', N'Republic of Cameroon', N'237'),
    (32, N'CA', N'Canada', N'Canada', N'1'),
    (33, N'CF', N'Central African Republic', N'Central African Republic', N'236'),
    (34, N'TD', N'Chad', N'Republic of Chad', N'235'),
    (35, N'CL', N'Chile', N'Republic of Chile', N'56'),
    (36, N'CN', N'China', N'People''s Republic of China', N'86'),
    (37, N'CO', N'Colombia', N'Republic of Colombia', N'57'),
    (38, N'KM', N'Comoros', N'Union of the Comoros', N'269'),
    (39, N'CG', N'Congo', N'Republic of the Congo', N'242'),
    (40, N'CR', N'Costa Rica', N'Republic of Costa Rica', N'506'),
    (41, N'CI', N'Ivory Coast', N'Republic of Côte d''Ivoire', N'225'),
    (42, N'HR', N'Croatia', N'Republic of Croatia', N'385'),
    (43, N'CU', N'Cuba', N'Republic of Cuba', N'53'),
    (44, N'CY', N'Cyprus', N'Republic of Cyprus', N'357'),
    (45, N'CZ', N'Czech Republic', N'Czech Republic', N'420'),
    (46, N'KP', N'North Korea', N'Democratic People''s Republic of Korea', N'850'),
    (47, N'CD', N'DR Congo', N'Democratic Republic of the Congo', N'243'),
    (48, N'DK', N'Denmark', N'Kingdom of Denmark', N'45'),
    (49, N'FO', N'Faroe Islands', N'Faroe Islands', N'298'),
    (50, N'GL', N'Greenland', N'Greenland', N'299'),
    (51, N'DJ', N'Djibouti', N'Republic of Djibouti', N'253'),
    (52, N'DM', N'Dominica', N'Commonwealth of Dominica', N'1-767'),
    (53, N'DO', N'Dominican Republic', N'Dominican Republic', N'1-809,1-829,1-849'),
    (54, N'EC', N'Ecuador', N'Republic of Ecuador', N'593'),
    (55, N'EG', N'Egypt', N'Arab Republic of Egypt', N'20'),
    (56, N'SV', N'El Salvador', N'Republic of El Salvador', N'503'),
    (57, N'GQ', N'Equatorial Guinea', N'Republic of Equatorial Guinea', N'240'),
    (58, N'ER', N'Eritrea', N'State of Eritrea', N'291'),
    (59, N'EE', N'Estonia', N'Republic of Estonia', N'372'),
    (60, N'ET', N'Ethiopia', N'Federal Democratic Republic of Ethiopia ', N'251'),
    (61, N'SZ', N'Swaziland', N'Kingdom of eSwatini', N'268'),
    (62, N'FJ', N'Fiji', N'Republic of Fiji', N'679'),
    (63, N'FI', N'Finland', N'Republic of Finland', N'358'),
    (64, N'FR', N'France', N'French Republic', N'33'),
    (65, N'GA', N'Gabon', N'Gabonese Republic', N'241'),
    (66, N'GM', N'The Gambia', N'Republic of the Gambia', N'220'),
    (67, N'GE', N'Georgia', N'Georgia', N'995'),
    (68, N'DE', N'Germany', N'Federal Republic of Germany', N'49'),
    (69, N'GH', N'Ghana', N'Republic of Ghana', N'233'),
    (70, N'GR', N'Greece', N'Hellenic Republic', N'30'),
    (71, N'GD', N'Grenada', N'Grenada', N'1-473'),
    (72, N'GT', N'Guatemala', N'Republic of Guatemala', N'502'),
    (73, N'GN', N'Guinea', N'Republic of Guinea', N'224'),
    (74, N'GW', N'Guinea-Bissau', N'Republic of Guinea-Bissau', N'245'),
    (75, N'GY', N'Guyana', N'Co-operative Republic of Guyana', N'592'),
    (76, N'HT', N'Haiti', N'Republic of Haiti', N'509'),
    (77, N'HN', N'Honduras', N'Republic of Honduras', N'504'),
    (78, N'HU', N'Hungary', N'Hungary', N'36'),
    (79, N'IS', N'Iceland', N'Iceland', N'358'),
    (80, N'IN', N'India', N'Republic of India', N'91'),
    (81, N'ID', N'Indonesia', N'Republic of Indonesia', N'62'),
    (82, N'IR', N'Iran', N'Islamic Republic of Iran', N'98'),
    (83, N'IQ', N'Iraq', N'Republic of Iraq', N'964'),
    (84, N'IE', N'Ireland', N'Republic of Ireland', N'353'),
    (85, N'IL', N'Israel', N'State of Israel', N'972'),
    (86, N'IT', N'Italy', N'Italian Republic', N'39'),
    (87, N'JM', N'Jamaica', N'Jamaica', N'1-876,1-658'),
    (88, N'JP', N'Japan', N'Japan', N'81'),
    (89, N'JO', N'Jordan', N'The Hashemite Kingdom of Jordan', N'962'),
    (90, N'KZ', N'Kazakhstan', N'Republic of Kazakhstan', N'7'),
    (91, N'EAT', N'Kenya', N'Republic of Kenya', N'254'),
    (92, N'KI', N'Kiribati', N'Republic of Kiribati', N'686'),
    (93, N'KW', N'Kuwait', N'State of Kuwait', N'965'),
    (94, N'KGT', N'Kyrgyzstan', N'Kyrgyz Republic', N'996'),
    (95, N'LA', N'Laos', N'Lao People''s Democratic Republic', N'856'),
    (96, N'LV', N'Latvia', N'Republic of Latvia', N'371'),
    (97, N'LB', N'Lebanon', N'Lebanese Republic', N'961'),
    (98, N'LS', N'Lesotho', N'Kingdom of Lesotho', N'266'),
    (99, N'LR', N'Liberia', N'Republic of Liberia', N'231'),
    (100, N'LY', N'Libya', N'State of Libya', N'218'),
    (101, N'LI', N'Liechtenstein', N'Principality of Liechtenstein', N'423'),
    (102, N'LT', N'Lithuania', N'Republic of Lithuania', N'370'),
    (103, N'LU', N'Luxembourg', N'Grand Duchy of Luxembourg', N'352'),
    (104, N'MG', N'Madagascar', N'Republic of Madagascar', N'261'),
    (105, N'MW', N'Malawi', N'Republic of Malawi', N'265'),
    (106, N'MY', N'Malaysia', N'Malaysia', N'60'),
    (107, N'MV', N'Maldives', N'Republic of Maldives', N'960'),
    (108, N'ML', N'Mali', N'Republic of Mali', N'223'),
    (109, N'MT', N'Malta', N'Republic of Malta', N'356'),
    (110, N'MH', N'Marshall Islands', N'Republic of the Marshall Islands', N'692'),
    (111, N'MR', N'Mauritania', N'Islamic Republic of Mauritania', N'222'),
    (112, N'MU', N'Mauritius', N'Republic of Mauritius', N'230'),
    (113, N'MX', N'Mexico', N'United Mexican States', N'52'),
    (114, N'FM', N'Federated States of Micronesia', N'Federated States of Micronesia', N'691'),
    (115, N'MC', N'Monaco', N'Principality of Monaco', N'377'),
    (116, N'MN', N'Mongolia', N'Mongolia', N'976'),
    (117, N'ME', N'Montenegro', N'Montenegro', N'382'),
    (118, N'MA', N'Morocco', N'Kingdom of Morocco', N'212'),
    (119, N'MZ', N'Mozambique', N'Republic of Mozambique', N'258'),
    (120, N'MM', N'Myanmar', N'Republic of the Union of Myanmar', N'95'),
    (121, N'NA', N'Namibia', N'Republic of Namibia', N'264'),
    (122, N'NR', N'Nauru', N'Republic of Nauru', N'674'),
    (123, N'NP', N'Nepal', N'Federal Democratic Republic of Nepal', N'977'),
    (124, N'NL', N'Netherlands', N'Kingdom of the Netherlands', N'31,297,599,1-721'),
    (125, N'NZ', N'New Zealand', N'New Zealand', N'64'),
    (126, N'NI', N'Nicaragua', N'Republic of Nicaragua', N'505'),
    (127, N'NE', N'Niger', N'Republic of the Niger', N'227'),
    (128, N'NG', N'Nigeria', N'Federal Republic of Nigeria', N'234'),
    (129, N'NO', N'Norway', N'Kingdom of Norway', N'47'),
    (130, N'OM', N'Oman', N'Sultanate of Oman', N'968'),
    (131, N'PK', N'Pakistan', N'Islamic Republic of Pakistan', N'92'),
    (132, N'PW', N'Palau', N'Republic of Palau', N'680'),
    (133, N'PS', N'Palestine', N'State of Palestine', N'970'),
    (134, N'PA', N'Panama', N'Republic of Panama', N'507'),
    (135, N'PG', N'Papua New Guinea', N'Independent State of Papua New Guinea', N'675'),
    (136, N'PY', N'Paraguay', N'Republic of Paraguay', N'595'),
    (137, N'PE', N'Peru', N'Republic of Peru', N'51'),
    (138, N'PH', N'Philippines', N'Republic of the Philippines ', N'63'),
    (139, N'PL', N'Poland', N'Republic of Poland', N'48'),
    (140, N'PT', N'Portugal', N'Portuguese Republic', N'351'),
    (141, N'QA', N'Qatar', N'State of Qatar', N'974'),
    (142, N'RO', N'Romania', N'Romania', N'40'),
    (143, N'RU', N'Russia', N'Russian Federation', N'7'),
    (144, N'RW', N'Rwanda', N'Republic of Rwanda', N'250'),
    (145, N'KN', N'Saint Kitts and Nevis', N'Federation of Saint Christopher and Nevis', N'1869'),
    (146, N'LC', N'Saint Lucia', N'Saint Lucia', N'1758'),
    (147, N'VC', N'Saint Vincent', N'Saint Vincent and the Grenadines', N'1784'),
    (148, N'WS', N'Samoa', N'Independent State of Samoa', N'685'),
    (149, N'SM', N'San Marino', N'Republic of San Marino', N'378'),
    (150, N'ST', N'São Tomé and Príncipe', N'Democratic Republic of São Tomé and Príncipe', N'239'),
    (151, N'SA', N'Saudi Arabia', N'Kingdom of Saudi Arabia', N'966'),
    (152, N'SN', N'Senegal', N'Republic of Senegal', N'221'),
    (153, N'RS', N'Serbia', N'Republic of Serbia', N'381'),
    (154, N'SC', N'Seychelles', N'Republic of Seychelles', N'248'),
    (155, N'SL', N'Sierra Leone', N'Republic of Sierra Leone', N'232'),
    (156, N'SG', N'Singapore', N'Republic of Singapore', N'65'),
    (157, N'SK', N'Slovakia', N'Slovak Republic', N'421'),
    (158, N'SI', N'Slovenia', N'Republic of Slovenia', N'386'),
    (159, N'SB', N'Solomon Islands', N'Solomon Islands', N'677'),
    (160, N'SO', N'Somalia', N'Federal Republic of Somalia', N'252'),
    (161, N'ZA', N'South Africa', N'Republic of South Africa', N'27'),
    (162, N'SS', N'South Sudan', N'Republic of South Sudan', N'211'),
    (163, N'ES', N'Spain', N'Kingdom of Spain', N'34'),
    (164, N'LK', N'Sri Lanka', N'Democratic Socialist Republic of Sri Lanka', N'94'),
    (165, N'SD', N'North Sudan', N'Republic of the Sudan', N'249'),
    (166, N'SR', N'Suriname', N'Republic of Suriname', N'597'),
    (167, N'SZ', N'Swaziland', N'Kingdom of Eswatini', N'268'),
    (168, N'SE', N'Sweden', N'Kingdom of Sweden', N'46'),
    (169, N'CH', N'Switzerland', N'Swiss Confederation', N'41'),
    (170, N'SY', N'Syria', N'Syrian Arab Republic', N'963'),
    (171, N'TJ', N'Tajikistan', N'Republic of Tajikistan', N'992'),
    (172, N'TZ', N'Tanzania', N'United Republic of Tanzania', N'255'),
    (173, N'TH', N'Thailand', N'Kingdom of Thailand', N'66'),
    (174, N'TG', N'Togo', N'Togolese Republic', N'228'),
    (175, N'TO', N'Tonga', N'Kingdom of Tonga', N'676'),
    (176, N'TT', N'Trinidad and Tobago', N'Republic of Trinidad and Tobago', N'1 868'),
    (177, N'TN', N'Tunisia', N'Republic of Tunisia', N'216'),
    (178, N'TR', N'Turkey', N'Republic of Turkey', N'90'),
    (179, N'TM', N'Turkmenistan', N'Turkmenistan', N'993'),
    (180, N'TV', N'Tuvalu', N'Tuvalu', N'65'),
    (181, N'UG', N'Uganda', N'Republic of Uganda', N'256'),
    (182, N'UA', N'Ukraine', N'Ukraine', N'380'),
    (183, N'AE', N'United Arab Emirates', N'United Arab Emirates', N'971'),
    (184, N'GB', N'United Kingdom', N'United Kingdom', N'44'),
    (185, N'US', N'United States', N'United States of America', N'1'),
    (186, N'UY', N'Uruguay', N'Oriental Republic of Uruguay', N'598'),
    (187, N'UZ', N'Uzbekistan', N'Republic of Uzbekistan', N'998'),
    (188, N'VU', N'Vanuatu', N'Republic of Vanuatu', N'678'),
    (189, N'VA', N'Vatican City', N'State of Vatican City', N'349'),
    (190, N'VE', N'Venezuela', N'Bolivarian Republic of Venezuela', N'58'),
    (191, N'VN', N'Vietnam', N'Socialist Republic of Vietnam', N'84'),
    (192, N'YE', N'Yemen', N'Republic of Yemen', N'967'),
    (193, N'ZM', N'Zambia', N'Republic of Zambia', N'260'),
    (194, N'ZW', N'Zimbabwe', N'Republic of Zimbabwe', N'263')
GO