INSERT INTO dbo.CountryMaster
    (
        CountryId,
        ShortName,
        OfficialName,
        PhoneCode, -- Stored as csv
        ISO3166Code
    )
VALUES
    (1, N'Afghanistan', N'Islamic Republic of Afghanistan', N'93', N'AF'),
    (2, N'Albania', N'Republic of Albania', N'355', N'AL'),
    (3, N'Algeria', N'People''s Democratic Republic of Algeria', N'+213', N'DZ'),
    (4, N'Andorra', N'Principality of the Valleys of Andorra', N'+316', N'AD'),
    (5, N'Angola', N'Republic of Angola', N'+244', N'AO'),
    (6, N'Antigua and Barbuda', N'Antigua and Barbuda', N'+1-268', N'AG'),
    (7, N'Argentina', N'Argentine Republic', N'+54', N'AR'),
    (8, N'Armenia', N'Republic of Armenia', N'+378', N'AM'),
    (9, N'Australia', N'Commonwealth of Australia', N'+61', N'AU'),
    (10, N'Austria', N'Republic of Austria', N'+43', N'AT'),
    (11, N'Azerbaijan', N'Republic of Azerbaijan ', N'+994', N'AZ'),
    (12, N'The Bahamas', N'Commonwealth of The Bahamas', N'+1 242', N'BS'),
    (13, N'Bahrain', N'Kingdom of Bahrain', N'+973', N'BH'),
    (14, N'Bangladesh', N'People''s Republic of Bangladesh', N'+880', N'BD'),
    (15, N'Barbados', N'Barbados', N'+1-246', N'BB'),
    (16, N'Belarus', N'Republic of Belarus', N'+375', N'BY'),
    (17, N'Belgium', N'Kingdom of Belgium', N'+32', N'BE'),
    (18, N'Belize', N'Belize', N'+501', N'BZ'),
    (19, N'Benin', N'Republic of Benin', N'+229', N'BJ'),
    (20, N'Bhutan', N'Kingdom of Bhutan', N'+975', N'BT'),
    (21, N'Bolivia', N'Plurinational State of Bolivia', N'+591', N'BO'),
    (22, N'Bosnia and Herzegovina', N'Bosnia and Herzegovina', N'+387', N'BA'),
    (23, N'Botswana', N'Republic of Botswana', N'+267', N'BW'),
    (24, N'Brazil', N'Federative Republic of Brazil', N'+55', N'BR'),
    (25, N'Brunei', N'Nation of Brunei, the Abode of Peace', N'+673', N'BN'),
    (26, N'Bulgaria', N'Republic of Bulgaria', N'+359', N'BG'),
    (27, N'Burkina Faso', N'Burkina Faso', N'+226', N'BF'),
    (28, N'Burundi', N'Republic of Burundi', N'+257', N'BI'),
    (29, N'Cabo Verde', N'Republic of Cabo Verde', N'+238', N'CV'),
    (30, N'Cambodia', N'Kingdom of Cambodia', N'+855', N'KH'),
    (31, N'Cameroon', N'Republic of Cameroon', N'+237', N'CM'),
    (32, N'Canada', N'Canada', N'+1', N'CA'),
    (33, N'Central African Republic', N'Central African Republic', N'+236', N'CF'),
    (34, N'Chad', N'Republic of Chad', N'+235', N'TD'),
    (35, N'Chile', N'Republic of Chile', N'+56', N'CL'),
    (36, N'China', N'People''s Republic of China', N'+86', N'CN'),
    (37, N'Colombia', N'Republic of Colombia', N'+57', N'CO'),
    (38, N'Comoros', N'Union of the Comoros', N'+269', N'KM'),
    (39, N'Congo', N'Republic of the Congo', N'+242', N'CG'),
    (40, N'Costa Rica', N'Republic of Costa Rica', N'+506', N'CR'),
    (41, N'Ivory Coast', N'Republic of Côte d''Ivoire', N'+225', N'CI'),
    (42, N'Croatia', N'Republic of Croatia', N'+385', N'HR'),
    (43, N'Cuba', N'Republic of Cuba', N'+53', N'CU'),
    (44, N'Cyprus', N'Republic of Cyprus', N'+357', N'CY'),
    (45, N'Czech Republic', N'Czech Republic', N'+420', N'CZ'),
    (46, N'North Korea', N'Democratic People''s Republic of Korea', N'+850', N'KP'),
    (47, N'DR Congo', N'Democratic Republic of the Congo', N'+243', N'CD'),
    (48, N'Denmark', N'Kingdom of Denmark', N'+45', N'DK'),
    (49, N'Faroe Islands', N'Faroe Islands', N'+298', N'FO'),
    (50, N'Greenland', N'Greenland', N'+299', N'GL'),
    (51, N'Djibouti', N'Republic of Djibouti', N'+253', N'DJ'),
    (52, N'Dominica', N'Commonwealth of Dominica', N'+1-767', N'DM'),
    (53, N'Dominican Republic', N'Dominican Republic', N'+1-809,+1-829,+1-849', N'DO'),
    (54, N'Ecuador', N'Republic of Ecuador', N'+593', N'EC'),
    (55, N'Egypt', N'Arab Republic of Egypt', N'+20', N'EG'),
    (56, N'El Salvador', N'Republic of El Salvador', N'+503', N'SV'),
    (57, N'Equatorial Guinea', N'Republic of Equatorial Guinea', N'+240', N'GQ'),
    (58, N'Eritrea', N'State of Eritrea', N'+291', N'ER'),
    (59, N'Estonia', N'Republic of Estonia', N'+372', N'EE'),
    (60, N'Ethiopia', N'Federal Democratic Republic of Ethiopia ', N'+251', N'ET'),
    (61, N'Swaziland', N'Kingdom of eSwatini', N'+268', N'SZ'),
    (62, N'Fiji', N'Republic of Fiji', N'+679', N'FJ'),
    (63, N'Finland', N'Republic of Finland', N'+358', N'FI'),
    (64, N'France', N'French Republic', N'+33', N'FR'),
    (65, N'Gabon', N'Gabonese Republic', N'+241', N'GA'),
    (66, N'The Gambia', N'Republic of the Gambia', N'+220', N'GM'),
    (67, N'Georgia', N'Georgia', N'+995', N'GE'),
    (68, N'Germany', N'Federal Republic of Germany', N'+49', N'DE'),
    (69, N'Ghana', N'Republic of Ghana', N'+233', N'GH'),
    (70, N'Greece', N'Hellenic Republic', N'+30', N'GR'),
    (71, N'Grenada', N'Grenada', N'+1-473', N'GD'),
    (72, N'Guatemala', N'Republic of Guatemala', N'+502', N'GT'),
    (73, N'Guinea', N'Republic of Guinea', N'+224', N'GN'),
    (74, N'Guinea-Bissau', N'Republic of Guinea-Bissau', N'+245', N'GW'),
    (75, N'Guyana', N'Co-operative Republic of Guyana', N'+592', N'GY'),
    (76, N'Haiti', N'Republic of Haiti', N'+509', N'HT'),
    (77, N'Honduras', N'Republic of Honduras', N'+504', N'HN'),
    (78, N'Hungary', N'Hungary', N'+36', N'HU'),
    (79, N'Iceland', N'Iceland', N'358', N'IS'),
    (80, N'India', N'Republic of India', N'+91', N'IN'),
    (81, N'Indonesia', N'Republic of Indonesia', N'+62', N'ID'),
    (82, N'Iran', N'Islamic Republic of Iran', N'+98', N'IR'),
    (83, N'Iraq', N'Republic of Iraq', N'+964', N'IQ'),
    (84, N'Ireland', N'Republic of Ireland', N'+353', N'IE'),
    (85, N'Israel', N'State of Israel', N'+972', N'IL'),
    (86, N'Italy', N'Italian Republic', N'+39', N'IT'),
    (87, N'Jamaica', N'Jamaica', N'1+-876,+1-658', N'JM'),
    (88, N'Japan', N'Japan', N'+81', N'JP'),
    (89, N'Jordan', N'The Hashemite Kingdom of Jordan', N'+962', N'JO'),
    (90, N'Kazakhstan', N'Republic of Kazakhstan', N'7', N'KZ'),
    (91, N'Kenya', N'Republic of Kenya', N'+254', N'EAT'),
    (92, N'Kiribati', N'Republic of Kiribati', N'+686', N'KI'),
    (93, N'Kuwait', N'State of Kuwait', N'+965', N'KW'),
    (94, N'Kyrgyzstan', N'Kyrgyz Republic', N'+996', N'KGT'),
    (95, N'Laos', N'Lao People''s Democratic Republic', N'+856', N'LA'),
    (96, N'Latvia', N'Republic of Latvia', N'+371', N'LV'),
    (97, N'Lebanon', N'Lebanese Republic', N'+961', N'LB'),
    (98, N'Lesotho', N'Kingdom of Lesotho', N'+266', N'LS'),
    (99, N'Liberia', N'Republic of Liberia', N'+231', N'LR'),
    (100, N'Libya', N'State of Libya', N'+218', N'LY'),
    (101, N'Liechtenstein', N'Principality of Liechtenstein', N'+423', N'LI'),
    (102, N'Lithuania', N'Republic of Lithuania', N'+370', N'LT'),
    (103, N'Luxembourg', N'Grand Duchy of Luxembourg', N'+352', N'LU'),
    (104, N'Madagascar', N'Republic of Madagascar', N'+261', N'MG'),
    (105, N'Malawi', N'Republic of Malawi', N'+265', N'MW'),
    (106, N'Malaysia', N'Malaysia', N'+60', N'MY'),
    (107, N'Maldives', N'Republic of Maldives', N'+960', N'MV'),
    (108, N'Mali', N'Republic of Mali', N'+223', N'ML'),
    (109, N'Malta', N'Republic of Malta', N'+356', N'MT'),
    (110, N'Marshall Islands', N'Republic of the Marshall Islands', N'+692', N'MH'),
    (111, N'Mauritania', N'Islamic Republic of Mauritania', N'+222', N'MR'),
    (112, N'Mauritius', N'Republic of Mauritius', N'+230', N'MU'),
    (113, N'Mexico', N'United Mexican States', N'+52', N'MX'),
    (114, N'Federated States of Micronesia', N'Federated States of Micronesia', N'+691', N'FM'),
    (115, N'Monaco', N'Principality of Monaco', N'+377', N'MC'),
    (116, N'Mongolia', N'Mongolia', N'+976', N'MN'),
    (117, N'Montenegro', N'Montenegro', N'+382', N'ME'),
    (118, N'Morocco', N'Kingdom of Morocco', N'+212', N'MA'),
    (119, N'Mozambique', N'Republic of Mozambique', N'+258', N'MZ'),
    (120, N'Myanmar', N'Republic of the Union of Myanmar', N'+95', N'MM'),
    (121, N'Namibia', N'Republic of Namibia', N'+264', N'NA'),
    (122, N'Nauru', N'Republic of Nauru', N'+674', N'NR'),
    (123, N'Nepal', N'Federal Democratic Republic of Nepal', N'+977', N'NP'),
    (124, N'Netherlands', N'Kingdom of the Netherlands', N'+31,+297,+599,+1-721', N'NL'),
    (125, N'New Zealand', N'New Zealand', N'+64', N'NZ'),
    (126, N'Nicaragua', N'Republic of Nicaragua', N'+505', N'NI'),
    (127, N'Niger', N'Republic of the Niger', N'+227', N'NE'),
    (128, N'Nigeria', N'Federal Republic of Nigeria', N'+234', N'NG'),
    (129, N'Norway', N'Kingdom of Norway', N'+47', N'NO'),
    (130, N'Oman', N'Sultanate of Oman', N'+968', N'OM'),
    (131, N'Pakistan', N'Islamic Republic of Pakistan', N'+92', N'PK'),
    (132, N'Palau', N'Republic of Palau', N'+680', N'PW'),
    (133, N'Palestine', N'State of Palestine', N'+970', N'PS'),
    (134, N'Panama', N'Republic of Panama', N'+507', N'PA'),
    (135, N'Papua New Guinea', N'Independent State of Papua New Guinea', N'+675', N'PG'),
    (136, N'Paraguay', N'Republic of Paraguay', N'+595', N'PY'),
    (137, N'Peru', N'Republic of Peru', N'+51', N'PE'),
    (138, N'Philippines', N'Republic of the Philippines ', N'+63', N'PH'),
    (139, N'Poland', N'Republic of Poland', N'+48', N'PL'),
    (140, N'Portugal', N'Portuguese Republic', N'+351', N'PT'),
    (141, N'Qatar', N'State of Qatar', N'+974', N'QA'),
    (142, N'Romania', N'Romania', N'+40', N'RO'),
    (143, N'Russia', N'Russian Federation', N'+7', N'RU'),
    (144, N'Rwanda', N'Republic of Rwanda', N'+250', N'RW'),
    (145, N'Saint Kitts and Nevis', N'Federation of Saint Christopher and Nevis', N'+1869', N'KN'),
    (146, N'Saint Lucia', N'Saint Lucia', N'+1758', N'LC'),
    (147, N'Saint Vincent', N'Saint Vincent and the Grenadines', N'+1784', N'VC'),
    (148, N'Samoa', N'Independent State of Samoa', N'+685', N'WS'),
    (149, N'San Marino', N'Republic of San Marino', N'+378', N'SM'),
    (150, N'São Tomé and Príncipe', N'Democratic Republic of São Tomé and Príncipe', N'+239', N'ST'),
    (151, N'Saudi Arabia', N'Kingdom of Saudi Arabia', N'+966', N'SA'),
    (152, N'Senegal', N'Republic of Senegal', N'+221', N'SN'),
    (153, N'Serbia', N'Republic of Serbia', N'+381', N'RS'),
    (154, N'Seychelles', N'Republic of Seychelles', N'+248', N'SC'),
    (155, N'Sierra Leone', N'Republic of Sierra Leone', N'+232', N'SL'),
    (156, N'Singapore', N'Republic of Singapore', N'+65', N'SG'),
    (157, N'Slovakia', N'Slovak Republic', N'+421', N'SK'),
    (158, N'Slovenia', N'Republic of Slovenia', N'+386', N'SI'),
    (159, N'Solomon Islands', N'Solomon Islands', N'+677', N'SB'),
    (160, N'Somalia', N'Federal Republic of Somalia', N'+252', N'SO'),
    (161, N'South Africa', N'Republic of South Africa', N'+27', N'ZA'),
    (162, N'South Sudan', N'Republic of South Sudan', N'+211', N'SS'),
    (163, N'Spain', N'Kingdom of Spain', N'+34', N'ES'),
    (164, N'Sri Lanka', N'Democratic Socialist Republic of Sri Lanka', N'+94', N'LK'),
    (165, N'North Sudan', N'Republic of the Sudan', N'+249', N'SD'),
    (166, N'Suriname', N'Republic of Suriname', N'+597', N'SR'),
    (167, N'Swaziland', N'Kingdom of Eswatini', N'+268', N'SZ'),
    (168, N'Sweden', N'Kingdom of Sweden', N'+46', N'SE'),
    (169, N'Switzerland', N'Swiss Confederation', N'+41', N'CH'),
    (170, N'Syria', N'Syrian Arab Republic', N'+963', N'SY'),
    (171, N'Tajikistan', N'Republic of Tajikistan', N'+992', N'TJ'),
    (172, N'Tanzania', N'United Republic of Tanzania', N'+255', N'TZ'),
    (173, N'Thailand', N'Kingdom of Thailand', N'+66', N'TH'),
    (174, N'Togo', N'Togolese Republic', N'+228', N'TG'),
    (175, N'Tonga', N'Kingdom of Tonga', N'+676', N'TO'),
    (176, N'Trinidad and Tobago', N'Republic of Trinidad and Tobago', N'+1 868', N'TT'),
    (177, N'Tunisia', N'Republic of Tunisia', N'+216', N'TN'),
    (178, N'Turkey', N'Republic of Turkey', N'+90', N'TR'),
    (179, N'Turkmenistan', N'Turkmenistan', N'+993', N'TM'),
    (180, N'Tuvalu', N'Tuvalu', N'+65', N'TV'),
    (181, N'Uganda', N'Republic of Uganda', N'+256', N'UG'),
    (182, N'Ukraine', N'Ukraine', N'+380', N'UA'),
    (183, N'United Arab Emirates', N'United Arab Emirates', N'+971', N'AE'),
    (184, N'United Kingdom', N'United Kingdom', N'+44', N'GB'),
    (185, N'United States', N'United States of America', N'+1', N'US'),
    (186, N'Uruguay', N'Oriental Republic of Uruguay', N'598', N'UY'),
    (187, N'Uzbekistan', N'Republic of Uzbekistan', N'+998', N'UZ'),
    (188, N'Vanuatu', N'Republic of Vanuatu', N'+678', N'VU'),
    (189, N'Vatican City', N'State of Vatican City', N'+349', N'VA'),
    (190, N'Venezuela', N'Bolivarian Republic of Venezuela', N'+58', N'VE'),
    (191, N'Vietnam', N'Socialist Republic of Vietnam', N'+84', N'VN'),
    (192, N'Yemen', N'Republic of Yemen', N'+967', N'YE'),
    (193, N'Zambia', N'Republic of Zambia', N'+260', N'ZM'),
    (194, N'Zimbabwe', N'Republic of Zimbabwe', N'+263', N'ZW')
GO