INSERT INTO dbo.StateMaster
    (
        CountryId,
        StateName -- Administrative divisions
    )
VALUES

    -- Afghanistan
    -- Ref: https://en.wikipedia.org/wiki/Afghanistan#Administrative_divisions
    (1, N"Badakhshan"),
    (1, N"Badghis"),
    (1, N"Baghlan"),
    (1, N"Balkh"),
    (1, N"Bamyan"),
    (1, N"Daykundi"),
    (1, N"Farah"),
    (1, N"Faryab"),
    (1, N"Ghazni"),
    (1, N"Ghor"),
    (1, N"Helmand"),
    (1, N"Herat"),
    (1, N"Jowzjan"),
    (1, N"Kabul"),
    (1, N"Kandahar"),
    (1, N"Kapisa"),
    (1, N"Khost"),
    (1, N"Kunar"),
    (1, N"Kunduz"),
    (1, N"Laghman"),
    (1, N"Logar"),
    (1, N"Nangarhar"),
    (1, N"Nimruz"),
    (1, N"Nuristan"),
    (1, N"Oruzgan"),
    (1, N"Paktia"),
    (1, N"Paktika"),
    (1, N"Panjshir"),
    (1, N"Parwan"),
    (1, N"Samangan"),
    (1, N"Sar-e Pol"),
    (1, N"Takhar"),
    (1, N"Wardak"),
    (1, N"Zabul"),

    -- Albania
    -- Ref: https://en.wikipedia.org/wiki/Albania#Administrative_divisions
    (2, N"Shkodër"),
    (2, N"Kukës"),
    (2, N"Lezhë"),
    (2, N"Dibër"),
    (2, N"Durrës"),
    (2, N"Tiranë"),
    (2, N"Elbasan"),
    (2, N"Korçë"),
    (2, N"Fier"),
    (2, N"Berat"),
    (2, N"Vlorë"),
    (2, N"Gjirokastër"),

    -- Algeria
    -- Ref: https://en.wikipedia.org/wiki/Algeria#Administrative_divisions
    (3, N"Adrar"),
    (3, N"Chlef"),
    (3, N"Laghouat"),
    (3, N"Oum El Bouaghi"),
    (3, N"Batna"),
    (3, N"Béjaïa"),
    (3, N"Biskra"),
    (3, N"Béchar"),
    (3, N"Blida"),
    (3, N"Bouïra"),
    (3, N"Tamanrasset"),
    (3, N"Tébessa"),
    (3, N"Tlemcen"),
    (3, N"Tiaret"),
    (3, N"Tizi Ouzou"),
    (3, N"Algiers"),
    (3, N"Djelfa"),
    (3, N"Jijel"),
    (3, N"Sétif"),
    (3, N"Saïda"),
    (3, N"Skikda"),
    (3, N"Sidi Bel Abbès"),
    (3, N"Annaba"),
    (3, N"Guelma"),
    (3, N"Constantine"),
    (3, N"Médéa"),
    (3, N"Mostaganem"),
    (3, N"M'Sila"),
    (3, N"Mascara"),
    (3, N"Ouargla"),
    (3, N"Oran"),
    (3, N"El Bayadh"),
    (3, N"Illizi"),
    (3, N"Bordj Bou Arréridj"),
    (3, N"Boumerdes"),
    (3, N"El Taref"),
    (3, N"Tindouf"),
    (3, N"Tissemsilt"),
    (3, N"El Oued"),
    (3, N"Khenchela"),
    (3, N"Souk Ahras"),
    (3, N"Tipaza"),
    (3, N"Mila"),
    (3, N"Ain Defla"),
    (3, N"Naâma"),
    (3, N"Ain Timouchent"),
    (3, N"Ghardaia"),
    (3, N"Relizane"),

    -- Andorra
    -- Ref: https://en.wikipedia.org/wiki/Parishes_of_Andorra
    (4, N"Andorra la Vella"),
    (4, N"Canillo"),
    (4, N"Encamp"),
    (4, N"Escaldes-Engordany"),
    (4, N"La Massana"),
    (4, N"Ordino"),
    (4, N"Sant Julià de Lòria"),

    -- Angola
    -- Ref: https://en.wikipedia.org/wiki/Angola#Administrative_divisions
    (5, N"Bengo"),
    (5, N"Benguela"),
    (5, N"Bié"),
    (5, N"Cabinda"),
    (5, N"Cuando Cubango"),
    (5, N"Cuanza Norte"),
    (5, N"Cuanza Sul"),
    (5, N"Cunene"),
    (5, N"Huambo"),
    (5, N"Huíla"),
    (5, N"Luanda"),
    (5, N"Lunda Norte"),
    (5, N"Lunda Sul"),
    (5, N"Malanje"),
    (5, N"Moxico"),
    (5, N"Namibe"),
    (5, N"Uíge"),
    (5, N"Zaire"),

    -- Antigua and Barbuda
    -- Ref: https://en.wikipedia.org/wiki/Antigua_and_Barbuda#Administrative_divisions
    (6, N"Saint George"),
    (6, N"Saint John"),
    (6, N"Saint Mary"),
    (6, N"Saint Paul"),
    (6, N"Saint Peter"),
    (6, N"Saint Philip"),
    (6, N"Barbuda"),
    (6, N"Redonda"),

    -- Argentina
    -- Ref: https://en.wikipedia.org/wiki/Provinces_of_Argentina
    (7, N"Buenos Aires"),
    (7, N"Catamarca"),
    (7, N"Chaco"),
    (7, N"Chubut"),
    (7, N"Ciudad de Buenos Aires"),
    (7, N"Corrientes"),
    (7, N"Córdoba"),
    (7, N"Entre Ríos"),
    (7, N"Formosa"),
    (7, N"Jujuy"),
    (7, N"La Pampa"),
    (7, N"La Rioja"),
    (7, N"Mendoza"),
    (7, N"Misiones"),
    (7, N"Neuquén"),
    (7, N"Río Negro"),
    (7, N"Salta"),
    (7, N"San Juan"),
    (7, N"San Luis"),
    (7, N"Santa Cruz"),
    (7, N"Santa Fe"),
    (7, N"Santiago del Estero"),
    (7, N"Tierra del Fuego"),
    (7, N"Tucumán"),

    -- Armenia
    -- Ref: https://en.wikipedia.org/wiki/Armenia#Administrative_divisions
    (8, N"Aragatsotn"),
    (8, N"Ararat"),
    (8, N"Armavir"),
    (8, N"Gegharkunik"),
    (8, N"Kotayk"),
    (8, N"Lori"),
    (8, N"Shirak"),
    (8, N"Syunik"),
    (8, N"Tavush"),
    (8, N"Vayots Dzor"),
    (8, N"Yerevan"),

    -- Australia
    -- Ref: https://en.wikipedia.org/wiki/Australia#States_and_territories
    (9, N"New South Wales"),
    (9, N"Queensland"),
    (9, N"South Australia"),
    (9, N"Tasmania"),
    (9, N"Victoria"),
    (9, N"Western Australia"),

    -- Austria
    -- Ref: https://en.wikipedia.org/wiki/Austria#Administrative_divisions
    (10, N"Burgenland"),
    (10, N"Carinthia"),
    (10, N"Lower Austria"),
    (10, N"Salzburg"),
    (10, N"Styria"),
    (10, N"Tyrol"),
    (10, N"Upper Austria"),
    (10, N"Vienna"),
    (10, N"Vorarlberg"),

    -- Azerbaijan
    -- Ref: https://en.wikipedia.org/wiki/Azerbaijan#Administrative_divisions
    (11, N"Absheron"),
    (11, N"Khizi"),
    (11, N"Baku"),
    (11, N"Sumqayit"),
    (11, N"Aghjabadi"),
    (11, N"Aghdash"),
    (11, N"Barda"),
    (11, N"Beylagan"),
    (11, N"Bilasuvar"),
    (11, N"Goychay"),
    (11, N"Hajigabul"),
    (11, N"Imishli"),
    (11, N"Kurdamir"),
    (11, N"Neftchala"),
    (11, N"Saatly"),
    (11, N"Sabirabad"),
    (11, N"Salyan"),
    (11, N"Ujar"),
    (11, N"Yevlakh"),
    (11, N"Zardab"),
    (11, N"Mingachevir"),
    (11, N"Shirvan"),
    (11, N"Yevlakh"),
    (11, N"Aghsu"),
    (11, N"Gobustan"),
    (11, N"Ismailly"),
    (11, N"Shamakhy"),
    (11, N"Aghstafa"),
    (11, N"Dashkasan"),
    (11, N"Gadabay"),
    (11, N"Gazakh"),
    (11, N"Goygol"),
    (11, N"Goranboy"),
    (11, N"Samukh"),
    (11, N"Shamkir"),
    (11, N"Tovuz"),
    (11, N"Ganja"),
    (11, N"Naftalan"),
    (11, N"Guba"),
    (11, N"Gusar"),
    (11, N"Khachmaz"),
    (11, N"Shabran"),
    (11, N"Siyazan"),
    (11, N"Gubadly"),
    (11, N"Kalbajar"),
    (11, N"Lachin"),
    (11, N"Zangilan"),
    (11, N"Astara"),
    (11, N"Jalilabad"),
    (11, N"Lankaran"),
    (11, N"Lerik"),
    (11, N"Masally"),
    (11, N"Yardimly"),
    (11, N"Lankaran"),
    (11, N"Babek"),
    (11, N"Julfa"),
    (11, N"Kangarli"),
    (11, N"Ordubad"),
    (11, N"Sadarak"),
    (11, N"Shahbuz"),
    (11, N"Sharur"),
    (11, N"Nakhchivan"),
    (11, N"Balakan"),
    (11, N"Gabala"),
    (11, N"Gakh"),
    (11, N"Oghuz"),
    (11, N"Shaki"),
    (11, N"Zaqatala"),
    (11, N"Shaki"),
    (11, N"Aghdam"),
    (11, N"Fuzuli"),
    (11, N"Jabrayil"),
    (11, N"Khojaly"),
    (11, N"Khojavend"),
    (11, N"Shusha"),
    (11, N"Tartar"),
    (11, N"Khankendi"),
    (11, N"Shusha"),

    -- The Bahamas
    -- Ref: https://en.wikipedia.org/wiki/The_Bahamas#Administrative_divisions
    (12, N"Acklins"),
    (12, N"Berry Islands"),
    (12, N"Bimini"),
    (12, N"Black Point, Exuma"),
    (12, N"Cat Island"),
    (12, N"Central Abaco"),
    (12, N"Central Andros"),
    (12, N"Central Eleuthera"),
    (12, N"City of Freeport, Grand Bahama"),
    (12, N"Crooked Island"),
    (12, N"East Grand Bahama"),
    (12, N"Exuma"),
    (12, N"Grand Cay, Abaco"),
    (12, N"Harbour Island, Eleuthera"),
    (12, N"Hope Town, Abaco"),
    (12, N"Inagua"),
    (12, N"Long Island"),
    (12, N"Mangrove Cay, Andros"),
    (12, N"Mayaguana"),
    (12, N"Moore's Island, Abaco"),
    (12, N"North Abaco"),
    (12, N"North Andros"),
    (12, N"North Eleuthera"),
    (12, N"Ragged Island"),
    (12, N"Rum Cay"),
    (12, N"San Salvador"),
    (12, N"South Abaco"),
    (12, N"South Andros"),
    (12, N"South Eleuthera"),
    (12, N"Spanish Wells, Eleuthera"),    
    (12, N"West Grand Bahama"),
    (12, N"New Providence"),

    -- Bahrain
    -- Ref: https://en.wikipedia.org/wiki/Bahrain#Governorates
    (13, N"Capital Governorate"),
    (13, N"Muharraq Governorate"),
    (13, N"Northern Governorate"),
    (13, N"Southern Governorate"),

    -- Bangladesh
    -- Ref: https://en.wikipedia.org/wiki/Bangladesh#Administrative_geography
    (14, N"Barisal"),
    (14, N"Chittagong"),
    (14, N"Dhaka"),
    (14, N"Khulna"),
    (14, N"Mymensingh"),
    (14, N"Rajshahi"),
    (14, N"Rangpur"),
    (14, N"Sylhet"),

    -- Barbados
    -- Ref: https://en.wikipedia.org/wiki/Barbados#Administrative_divisions
    (15, N"Christ Church"),
    (15, N"Saint Andrew"),
    (15, N"Saint George"),
    (15, N"Saint Thomas"),
    (15, N"Saint Philip"),
    (15, N"Saint Peter"),
    (15, N"Saint Michael"),
    (15, N"Saint Lucy"),
    (15, N"Saint Joseph"),
    (15, N"Saint John"),
    (15, N"Saint James"),

    -- Belarus
    -- Ref: https://en.wikipedia.org/wiki/Regions_of_Belarus
    (16, N"City of Minsk"),
    (16, N"Brest"),
    (16, N"Gomel"),
    (16, N"Grodno"),
    (16, N"Mogilev"),
    (16, N"Minsk"),
    (16, N"Vitebsk"),

    -- Belgium
    -- Ref: https://en.wikipedia.org/wiki/Provinces_of_Belgium
    (17, N"Antwerp"),
    (17, N"East Flanders"),
    (17, N"Flemish Brabant"),
    (17, N"Hainaut"),
    (17, N"Limburg"),
    (17, N"Liège"),
    (17, N"Luxembourg"),
    (17, N"Namur"),
    (17, N"Walloon Brabant"),
    (17, N"West Flanders"),
    (17, N"Brussels-Capital Region"),

    -- Belize
    -- Ref: https://en.wikipedia.org/wiki/Belize#Administrative_divisions
    (18, N"Belize"),
    (18, N"Cayo"),
    (18, N"Corozal"),
    (18, N"Orange Walk"),
    (18, N"Stann Creek"),
    (18, N"Toledo"),
    
    -- Benin
    -- Ref: https://en.wikipedia.org/wiki/Benin#Departments_and_communes
    (19, N"Alibori"),
    (19, N"Atakora"),
    (19, N"Atlantique"),
    (19, N"Borgou"),
    (19, N"Collines"),
    (19, N"Donga"),
    (19, N"Kouffo"),
    (19, N"Littoral"),
    (19, N"Mono"),
    (19, N"Ouémé"),
    (19, N"Plateau"),
    (19, N"Zou"),
    
    -- Bhutan
    -- Ref: https://en.wikipedia.org/wiki/Bhutan#Political_divisions
    (20, N"Bumthang"),
    (20, N"Chukha"),
    (20, N"Dagana"),
    (20, N"Gasa"),
    (20, N"Haa"),
    (20, N"Lhuntse"),
    (20, N"Mongar"),
    (20, N"Paro"),
    (20, N"Pemagatshel"),
    (20, N"Punakha"),
    (20, N"Samdrup Jongkhar"),
    (20, N"Samtse"),
    (20, N"Sarpang"),
    (20, N"Thimphu"),
    (20, N"Trashigang"),
    (20, N"Trashiyangtse"),
    (20, N"Trongsa"),
    (20, N"Tsirang"),
    (20, N"Wangdue Phodrang"),
    (20, N"Zhemgang"),
    
    -- Bolivia
    -- Ref: https://en.wikipedia.org/wiki/Bolivia#Administrative_divisions
    (21, N"Pando"),
    (21, N"La Paz"),
    (21, N"Beni"),
    (21, N"Oruro"),
    (21, N"Cochabamba"),
    (21, N"Santa Cruz"),
    (21, N"Potosí"),
    (21, N"Chuquisaca"),
    (21, N"Tarija"),
    
    -- Bosnia and Herzegovina
    -- Ref: https://en.wikipedia.org/wiki/Political_divisions_of_Bosnia_and_Herzegovina
    (22, N"Federation of Bosnia and Herzegovina"),
    (22, N"Republika Srpska"),
    
    -- Botswana
    -- Ref: https://en.wikipedia.org/wiki/Botswana#Administrative_divisions
    (23, N"Southern District"),
    (23, N"South-East District"),
    (23, N"Kweneng District"),
    (23, N"Kgatleng District"),
    (23, N"Central District"),
    (23, N"North-East District"),
    (23, N"North-West District"),
    (23, N"Ghanzi District"),
    (23, N"Kgalagadi District"),
    
    -- Brazil
    -- Ref: https://en.wikipedia.org/wiki/Brazil#Administrative_divisions
    (24, N"Acre"),
    (24, N"Alagoas"),
    (24, N"Amapá"),
    (24, N"Amazonas"),
    (24, N"Bahia"),
    (24, N"Ceará"),
    (24, N"Distrito Federal"),
    (24, N"Espírito Santo"),
    (24, N"Goiás"),
    (24, N"Maranhão"),
    (24, N"Mato Grosso"),
    (24, N"Mato Grosso do Sul"),
    (24, N"Minas Gerais"),
    (24, N"Paraná"),
    (24, N"Paraíba"),
    (24, N"Pará"),
    (24, N"Pernambuco"),
    (24, N"Piauí"),
    (24, N"Rio de Janeiro"),
    (24, N"Rio Grande do Norte"),
    (24, N"Rio Grande do Sul"),
    (24, N"Rondônia"),
    (24, N"Roraima"),
    (24, N"Santa Catarina"),
    (24, N"Sergipe"),
    (24, N"São Paulo"),
    (24, N"Tocantins"),
    (24, N"Federal District"),
    
    -- Brunei
    -- Ref: https://en.wikipedia.org/wiki/Brunei#Administrative_divisions
    (25, N"Belait"),
    (25, N"Brunei-Muara"),
    (25, N"Temburong"),
    (25, N"Tutong"),
    
    -- Bulgaria
    -- Ref: https://en.wikipedia.org/wiki/Bulgaria#Administrative_divisions
    (26, N"Sofia-Grad"),
    (26, N"Blagoevgrad"),
    (26, N"Burgas"),
    (26, N"Dobrich"),
    (26, N"Gabrovo"),
    (26, N"Haskovo"),
    (26, N"Kardzhali"),
    (26, N"Kyustendil"),
    (26, N"Lovech"),
    (26, N"Montana"),
    (26, N"Pazardzhik"),
    (26, N"Pernik"),
    (26, N"Pleven"),
    (26, N"Plovdiv"),
    (26, N"Razgrad"),
    (26, N"Ruse"),
    (26, N"Shumen"),
    (26, N"Silistra"),
    (26, N"Sliven"),
    (26, N"Smolyan"),
    (26, N"Sofia Province"),
    (26, N"Stara Zagora"),
    (26, N"Targovishte"),
    (26, N"Varna"),
    (26, N"Veliko Tarnovo"),
    (26, N"Vidin"),
    (26, N"Vratsa"),
    (26, N"Yambol"),
    
    -- Burkina Faso
    -- Ref: https://en.wikipedia.org/wiki/Regions_of_Burkina_Faso
    (27, N"Boucle du Mouhoun"),
    (27, N"Cascades"),
    (27, N"Centre"),
    (27, N"Centre-Est"),
    (27, N"Centre-Nord"),
    (27, N"Centre-Ouest"),
    (27, N"Centre-Sud"),
    (27, N"Est"),
    (27, N"Hauts-Bassins"),
    (27, N"Nord"),
    (27, N"Plateau-Central"),
    (27, N"Sahel"),
    (27, N"Sud-Ouest"),
    
    -- Burundi
    -- Ref: https://en.wikipedia.org/wiki/Burundi#Subdivisions
    (28, N"Bubanza"),
    (28, N"Bujumbura Mairie"),
    (28, N"Bujumbura Rural"),
    (28, N"Bururi"),
    (28, N"Cankuzo"),
    (28, N"Cibitoke"),
    (28, N"Gitega"),
    (28, N"Karuzi"),
    (28, N"Kayanza"),
    (28, N"Kirundo"),
    (28, N"Makamba"),
    (28, N"Muramvya"),
    (28, N"Muyinga"),
    (28, N"Mwaro"),
    (28, N"Ngozi"),
    (28, N"Rumonge"),
    (28, N"Rutana"),
    (28, N"Ruyigi"),
    
    -- Cabo Verde
    -- Ref: https://en.wikipedia.org/wiki/Cape_Verde#Administrative_divisions
    (29, N"Ribeira Grande"),
    (29, N"Paúl"),
    (29, N"Porto Novo"),
    (29, N"São Vicente"),
    (29, N"Ribeira Brava"),
    (29, N"Tarrafal de São Nicolau"),
    (29, N"Sal"),
    (29, N"Boa Vista"),
    (29, N"Maio"),
    (29, N"Praia"),
    (29, N"São Domingos"),
    (29, N"Santa Catarina"),
    (29, N"São Salvador do Mundo"),
    (29, N"Santa Cruz"),
    (29, N"São Lourenço dos Órgãos"),
    (29, N"Ribeira Grande de Santiago"),
    (29, N"São Miguel"),
    (29, N"Tarrafal"),
    (29, N"São Filipe"),
    (29, N"Santa Catarina do Fogo"),
    (29, N"Mosteiros"),
    (29, N"Brava"),
    
    -- Cambodia
    -- Ref: https://en.wikipedia.org/wiki/Cambodia#Administrative_divisions
    (30, N"Banteay Meanchey"),
    (30, N"Battambang"),
    (30, N"Kampong Cham"),
    (30, N"Kampong Chhnang"),
    (30, N"Kampong Speu"),
    (30, N"Kampong Thom"),
    (30, N"Kampot"),
    (30, N"Kandal"),
    (30, N"Kep"),
    (30, N"Koh Kong"),
    (30, N"Kratié"),
    (30, N"Mondulkiri"),
    (30, N"Oddar Meanchey"),
    (30, N"Pailin"),
    (30, N"Phnom Penh"),
    (30, N"Preah Sihanouk"),
    (30, N"Preah Vihear"),
    (30, N"Pursat"),
    (30, N"Prey Veng"),
    (30, N"Ratanakiri"),
    (30, N"Siem Reap"),
    (30, N"Stung Treng"),
    (30, N"Svay Rieng"),
    (30, N"Takéo"),
    (30, N"Tboung Khmom"),
    
    -- Cameroon
    -- Ref: https://en.wikipedia.org/wiki/Regions_of_Cameroon
    (31, N"Adamawa"),
    (31, N"Central Cameroon"),
    (31, N"East Cameroon"),
    (31, N"Far North Cameroon"),
    (31, N"Littoral Cameroon"),
    (31, N"North Cameroon"),
    (31, N"Northwest Cameroon"),
    (31, N"South Cameroon"),
    (31, N"Southwest Cameroon"),
    (31, N"West Cameroon"),
    
    -- Canada
    -- Ref: https://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada#Provinces
    (32, N"Alberta"),
    (32, N"British Columbia"),
    (32, N"Manitoba"),
    (32, N"New Brunswick"),
    (32, N"Newfoundland and Labrador"),
    (32, N"Nova Scotia"),
    (32, N"Ontario"),
    (32, N"Prince Edward Island"),
    (32, N"Quebec"),
    (32, N"Saskatchewan"),
    
    -- Central African Republic
    -- Ref: https://en.wikipedia.org/wiki/Central_African_Republic#Prefectures_and_sub-prefectures
    (33, N"Bamingui-Bangoran"),
    (33, N"Bangui"),
    (33, N"Basse-Kotto"),
    (33, N"Haut-Mbomou"),
    (33, N"Haute-Kotto"),
    (33, N"Kémo"),
    (33, N"Lobaye"),
    (33, N"Mambéré-Kadéï"),
    (33, N"Mbomou"),
    (33, N"Nana-Grébizi"),
    (33, N"Nana-Mambéré"),
    (33, N"Ombella-M'Poko"),
    (33, N"Ouaka"),
    (33, N"Ouham"),
    (33, N"Ouham-Pendé"),
    (33, N"Sangha-Mbaéré"),
    (33, N"Vakaga"),
    
    -- Chad
    -- Ref: https://en.wikipedia.org/wiki/Chad#Administrative_divisions
    (34, N"Bahr El Gazel"),
    (34, N"Batha"),
    (34, N"Borkou"),
    (34, N"Chari-Baguirmi"),
    (34, N"Ennedi-Est"),
    (34, N"Ennedi-Ouest"),
    (34, N"Guéra"),
    (34, N"Hadjer-Lamis"),
    (34, N"Kanem"),
    (34, N"Lac"),
    (34, N"Logone Occidental"),
    (34, N"Logone Oriental"),
    (34, N"Mandoul"),
    (34, N"Mayo-Kebbi Est"),
    (34, N"Mayo-Kebbi Ouest"),
    (34, N"Moyen-Chari"),
    (34, N"N'Djamena"),
    (34, N"Ouaddaï"),
    (34, N"Salamat"),
    (34, N"Sila"),
    (34, N"Tandjilé"),
    (34, N"Tibesti"),
    (34, N"Wadi Fira"),

    -- Chile
    -- Ref: https://en.wikipedia.org/wiki/Chile#Administrative_divisions
    (35, N"Arica y Parinacota"),
    (35, N"Tarapacá"),
    (35, N"Antofagasta"),
    (35, N"Atacama"),
    (35, N"Coquimbo"),
    (35, N"Valparaíso"),
    (35, N"Santiago Metropolitan"),
    (35, N"Libertador General Bernardo O'Higgins"),
    (35, N"Maule"),
    (35, N"Biobío"),
    (35, N"Araucanía"),
    (35, N"Los Ríos"),
    (35, N"Los Lagos"),
    (35, N"Aysén del General Carlos Ibáñez del Campo"),
    (35, N"Magallanes and Chilean Antarctica"),

    -- China
    -- Ref: https://en.wikipedia.org/wiki/Provinces_of_China#List_of_province-level_divisions
    (36, N"Anhui"),
    (36, N"Beijing"),
    (36, N"Chongqing"),
    (36, N"Fujian"),
    (36, N"Gansu"),
    (36, N"Guangdong"),
    (36, N"Guangxi Zhuang"),
    (36, N"Guizhou"),
    (36, N"Hainan"),
    (36, N"Hebei"),
    (36, N"Heilongjiang"),
    (36, N"Henan"),
    (36, N"Hong Kong"),
    (36, N"Hubei"),
    (36, N"Hunan"),
    (36, N"Inner Mongolia"),
    (36, N"Jiangsu"),
    (36, N"Jiangxi"),
    (36, N"Jilin"),
    (36, N"Liaoning"),
    (36, N"Macau"),
    (36, N"Ningxia Hui"),
    (36, N"Qinghai"),
    (36, N"Shaanxi"),
    (36, N"Shandong"),
    (36, N"Shanghai"),
    (36, N"Shanxi"),
    (36, N"Sichuan"),
    (36, N"Taiwan"),
    (36, N"Tianjin"),
    (36, N"Tibet"),
    (36, N"Xinjiang Uyghur"),
    (36, N"Yunnan"),
    (36, N"Zhejiang"),

    -- Colombia
    -- Ref: https://en.wikipedia.org/wiki/Colombia#Administrative_divisions
    (37, N"Amazonas"),
    (37, N"Antioquia"),
    (37, N"Arauca"),
    (37, N"Atlántico"),
    (37, N"Bolívar"),
    (37, N"Boyacá"),
    (37, N"Caldas"),
    (37, N"Caquetá"),
    (37, N"Casanare"),
    (37, N"Cauca"),
    (37, N"Cesar"),
    (37, N"Chocó"),
    (37, N"Córdoba"),
    (37, N"Cundinamarca"),
    (37, N"Guainía"),
    (37, N"Guaviare"),
    (37, N"Huila"),
    (37, N"La Guajira"),
    (37, N"Magdalena"),
    (37, N"Meta"),
    (37, N"Nariño"),
    (37, N"Norte de Santander"),
    (37, N"Putumayo"),
    (37, N"Quindío"),
    (37, N"Risaralda"),
    (37, N"San Andrés, Providencia and Santa Catalina"),
    (37, N"Santander"),
    (37, N"Sucre"),
    (37, N"Tolima"),
    (37, N"Valle del Cauca"),
    (37, N"Vaupés"),
    (37, N"Vichada"),
    (37, N"Bogotá"),

    -- Comoros
    -- Ref: 
    (38, N""),